### ISSUE TITLE
Update Laddr instance

### ISSUE THREAD

**Issue by jhibbets** [codeforraleigh/Captains-Task-List#52]
Reid - Heard last night that v 2.0 is out for laddr. Do we have plans to upgrade our instance or will we be going in a different direction?

**Comment by jhibbets** [comment]
Do we have a timeline for this; if not, I'm going to suggest we move to a completely new platform for our site.

**Comment by ChrisTheDBA** [comment]
I would tend to agree. Something like Wordpress or Drupal. This requires too specialized a skillset to work with.

**Comment by jhibbets** [comment]
Thoughts on using the CityCamp NC wordpress and seeing if we can have some
type of wordpress multi-site? One backend, two themes?

**Comment by ChrisTheDBA** [comment]
I personally like the idea of Wordpress. I know Wordpress and can help with it. Drupal would be a learning curve.

**Comment by ChrisTheDBA** [comment]
OK, we've got a working prototype at http://40.117.145.44/ it's very much a let's see works and what doesn't phase.  I still think we need to stick with WP or Drupal. Other brigades have released web platforms - Node.JS, Ruby, Emergent. Utimately I don't think will work for us since they require ongoing involvement of a dev resource. I want to make it so any brigade attendee can work on it.
